### ISSUE TITLE
SHOULD accept application/json and not make application/schema+json a MUST

### ISSUE THREAD

**Issue by n2ygk** [hyperjump-io/json-schema-core#9]
I suggest you strictly follow the [json-schema spec](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-8.1.1) and not make `Content-type: application/schema+json` mandatory when the spec uses `SHOULD` and not `MUST`.

https://github.com/hyperjump-io/json-schema-core/blob/1feb331a392e9db2fecbe304f05dbb9516b1cca9/lib/schema.js#L172-L173

Here's a breaking example that would otherwise work fine:

```json
{
    "$id": "https://example.com/geographical-location.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "Product",
    "description": "A product from Acme's catalog",
    "type": "object",
    "properties": {
        "id": {
            "description": "The unique identifier for a product",
            "type": "integer"
        },
        "warehouse_location": {
             "description": "Coordinates of the warehouse with the product",
             "$ref": "https://json-schema.org/learn/examples/geographical-location.schema.json"
        }
    },
    "required": ["id"],
    "additionalProperties": false
}
```

This throws: `Error: https://json-schema.org/learn/examples/geographical-location.schema.json is not a schema. Found a document with media type: application/json`

If you allow the more generic `application/json` Content-type, a superset of `application/schema+json`, then the above would work instead of throwing a premature error. You do further parsing of the JSON to determine if it really is a schema doc here so there's not much downside in being a forgiving parser:

https://github.com/hyperjump-io/json-schema-core/blob/1feb331a392e9db2fecbe304f05dbb9516b1cca9/lib/schema.js#L32-L40

**Comment by jdesrosiers** [comment]
After giving this a lot of thought, I want to leave the behavior as it is. However, I would be ok with adding a configuration of some sort to enable a lenient mode that would allow the implementation to process anything that it fetches as a schema.

If I put a URL in a web browser and I get back a document that has HTML, but uses a `plain/text` content type, I wouldn't expect it to render a web page, I'd expect to see HTML code. JSON Schema is built on top of web standards which makes implementations like this effectively a web client so it should function like a well behaved web client. In the future I might want to add support for other types of validation engines and there's no reason why you couldn't reference from a JSON Schema to something else. If I just treat everything as a JSON Schema, I couldn't support something like that.

I did consider that maybe because JSON Schema is JSON, I could accept JSON and run it through the algorithm as if it was a JSON Schema. The main problem with that is that JSON doesn't define semantics for URI fragments. That feature is added by `application/schema+json`. So, if I pass a JSON document through instead of a Schema document, any local references (such as `#/$defs/foo`), would always point to the root of the JSON document, not the location the fragment points to. Although that would be technically correct behavior in that situation, it will undoubtedly be considered a bug by anyone that comes across it.

Regarding compatibility with the JSON Schema spec, I don't think there's an issue. The spec talks about how you should serve schemas, but doesn't say anything about what clients should accept.

> If this URI identifies a retrievable resource, that resource SHOULD be of media type "application/schema+json".

Here's the definition of SHOULD

> **SHOULD**   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

So, the way I interpret the JSON Schema spec is that, there may exist valid reasons in particular circumstances to not serve schemas with `application/schema+json`, but before using another content type you should understand that implementations might not recognize the document as a schema.

**Comment by n2ygk** [comment]
From a practical perspective, GitHub Pages does not allow one to specify a content-type of `application/schema+json` and instead sends `application/json` so examples from json-schema.org can't be $ref'd.

**Comment by jdesrosiers** [comment]
Oh, I agree that there are cases where you can't get around it. That's why I'm ok with adding a flag to allow it. I'm just not ok with it being the default behavior.

A better solution is to register the `schema.json` file extension so Github Pages will serve the right content-type (https://github.com/json-schema-org/json-schema-spec/issues/1130). However, I'm not too worried about the examples on json-schema.org. They aren't there for people to `$ref`. Implementations are not expected to fetch references. You're expected to download the examples and load them into a validator locally.

**Comment by n2ygk** [comment]
At least one validator in fact does allow directly downloading the $ref:
https://www.jsonschemavalidator.net/.

**Comment by jdesrosiers** [comment]
That's fine. Different implementations can make different decisions. Remember that fetching a schema over the network or file system is not something the specification defines. Implementations are explicitly not expected to do this. So, if they do, there are no rules about how it must be done. I chose to follow web standards closely. Others might not care. Both are allowed.

Honestly, I'm a bit surprised about the push back. Is adding a configuration flag to enable this behavior not good enough? Is it terribly important that it be the default behavior?

**Comment by ioggstream** [comment]
https://github.com/hyperjump-io/json-schema-core/issues/9#issuecomment-933774929 duly noted https://github.com/ietf-wg-httpapi/mediatypes/issues/7

**Comment by jdesrosiers** [comment]
I added support for custom media type handlers. If you want to configure it to assume plain JSON is a JSON Schema you can do this,

```javascript
JsonSchema.addMediaTypePlugin("application/json", {
  parse: async (response) => await response.json(),
  matcher: (path) => path.endsWith(".json")
});
```

Or, if you want absolutely anything to be assumed to be a JSON Schema you can do this,

```javascript
JsonSchema.addMediaTypePlugin("application/octet-stream", {
  parse: async (response) => await response.json(),
  matcher: (path) => true
});
```
